// ─────────────────────────────────────────
// TermsPage
// Terms of service for Vocalendar
// Covers usage rules and limitations
// ─────────────────────────────────────────

import { Link } from "react-router-dom";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import { ROUTES } from "../constants/routes";

const Section = ({ title, children }) => (
  <div className="flex flex-col gap-3">
    <h2 className="text-xl font-bold text-gray-900">{title}</h2>
    <div className="text-gray-600 leading-relaxed flex flex-col gap-2">
      {children}
    </div>
  </div>
);

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />

      <main className="flex-1">
        <div className="max-w-3xl mx-auto px-6 py-16 flex flex-col gap-10">

          {/* ── header ── */}
          <div className="flex flex-col gap-3">
            <p className="text-blue-600 text-sm font-semibold uppercase tracking-wider">
              Legal
            </p>
            <h1 className="text-4xl font-bold text-gray-900">Terms of Service</h1>
            <p className="text-gray-400 text-sm">Last updated: July 6, 2026</p>
            <p className="text-gray-600 leading-relaxed">
              By using Vocalendar, you agree to these terms. Please read them carefully.
            </p>
          </div>

          <hr className="border-gray-100" />

          <Section title="What Vocalendar is">
            <p>
              Vocalendar is a voice-first task capture tool that transcribes
              your voice, extracts task details using AI, and saves events
              to your Google Calendar. It is provided as-is for personal
              productivity use.
            </p>
          </Section>

          <Section title="Acceptable use">
            <p>You agree to use Vocalendar only for lawful purposes. You must not:</p>
            <ul className="list-disc list-inside flex flex-col gap-1 ml-2">
              <li>Use the service to store illegal, harmful, or offensive content</li>
              <li>Attempt to reverse engineer, copy, or redistribute the application</li>
              <li>Use automated tools to abuse the API or circumvent rate limits</li>
              <li>Impersonate other users or provide false information</li>
              <li>Use the service in a way that could damage or overload our infrastructure</li>
            </ul>
          </Section>

          <Section title="Intellectual property">
            <p>
              Vocalendar, including its source code, design, and content,
              is the intellectual property of Kushal. All rights reserved.
            </p>
            <p>
              You may not copy, modify, distribute, sell, or create derivative
              works based on Vocalendar without explicit written permission.
            </p>
            <p>
              Your task data belongs to you. We claim no ownership over
              the content you create using Vocalendar.
            </p>
          </Section>

          <Section title="Google Calendar integration">
            <p>
              Vocalendar integrates with Google Calendar via the Google
              Calendar API. By connecting your Google account, you authorize
              Vocalendar to create calendar events on your behalf.
            </p>
            <p>
              You can revoke this authorization at any time. Vocalendar
              is not responsible for events already created before revocation.
            </p>
          </Section>

          <Section title="AI-generated content">
            <p>
              Task details extracted from your voice are generated by AI
              (Groq's LLaMA model). While we strive for accuracy, AI
              extraction may occasionally produce incorrect results.
            </p>
            <p>
              You are always shown a confirmation step before anything is
              saved to your calendar. You are responsible for reviewing
              and confirming extracted details before saving.
            </p>
          </Section>

          <Section title="Service availability">
            <p>
              Vocalendar is provided as-is with no guarantee of uptime
              or availability. We may modify, suspend, or discontinue
              the service at any time without notice.
            </p>
            <p>
              The free tier may have usage limits. We reserve the right
              to throttle or restrict access to prevent abuse.
            </p>
          </Section>

          <Section title="Limitation of liability">
            <p>
              Vocalendar is not liable for any missed tasks, appointments,
              or calendar errors resulting from incorrect AI extraction,
              service downtime, or any other cause.
            </p>
            <p>
              Always verify important events in your Google Calendar directly.
              Do not rely solely on Vocalendar for critical scheduling.
            </p>
          </Section>

          <Section title="Changes to these terms">
            <p>
              We may update these terms at any time. Continued use of
              Vocalendar after changes constitutes acceptance of the
              new terms. We will update the "Last updated" date above
              when changes are made.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these terms? Contact Kushal at{" "}
              <a
                href="mailto:kushalkalsariya1825@gmail.com"
                className="text-blue-600 hover:underline"
              >
                kushalkalsariya1825@gmail.com
              </a>
            </p>
          </Section>

          {/* ── back link ── */}
          <Link
            to={ROUTES.LANDING}
            className="text-blue-600 hover:text-blue-500 text-sm font-medium transition-colors w-fit"
          >
            ← Back to home
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}